const User = require("../models/User");

const userData = [
  {
    name: "Bob Smith",
    email: "bob@email.com",
    password: "password1",
    age: 21,
    img: "https://randomuser.me/api/portraits/men/40.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe: "tall dark and handsome",
    location: "birmingham",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "John James",
    email: "john@email.com",
    password: "password1",
    age: 24,
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    gender: "other",
    sexuality: "bisexual",
    aboutMe: "good things come in small packages",
    location: "coventry",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Lynn Peck",
    email: "lynn.peck@example.com",
    password: "dupont",
    age: 25,
    img: "https://randomuser.me/api/portraits/women/84.jpg",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I am well-balanced and stable, but willing to let you knock me off my feet",
    location: "Birmingham",
    height: 1.75,
    build: "athletic",
    seriousness: "medium",
  },

  {
    name: "Wanda Mendoza",
    email: "wanda.mendoza@example.com",
    password: "brown1",
    age: 41,
    img: "https://randomuser.me/api/portraits/women/71.jpg",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "I can guarantee you won't find anybody else like me.",
    location: "Leicester",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },

  {
    name: "Eli Wood",
    email: "eli.wood@example.com",
    age: 28,
    password: "chrysler",
    img: "https://randomuser.me/api/portraits/men/75.jpg",
    gender: "male",
    sexuality: "bisexual",
    aboutMe:
      "I am strong enough to protect you and soft enough to melt your heart..",
    location: "Leicester",
    height: 1.65,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Leanne Gallagher",
    email: "leanne_gallag@live.co.uk",
    password: "Password123!!",
    age: 29,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DHCF7M40-9dc481246e1e-512",
    gender: "female",
    sexuality: "bisexual",
    aboutMe:
      "Forget what hurt you in the past. It wasn't me. I'm like the opposite of that person!",
    location: "Coventry",
    height: 1.65,
    build: "large",
    seriousness: "low",
  },

  {
    name: "Fahra Akhlaq",
    email: "Fahra@email.com",
    password: "Password123",
    age: 33,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CY4F3BLP-5638e5955f09-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "As long as you think I'm awesome, we will get along just fine.",
    location: "Birmingham",
    height: 1.65,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Sumaia Sorna",
    email: "Sumaia@email.com",
    password: "Password123!!",
    age: 32,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02D2H7RXM1-0f957010b3cf-51212",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I'm not here to be an average partner, I'm here to be an awesome partner.",
    location: "Wolverhampton",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },

  {
    name: "Intisar Mohamed  ",
    email: "Intisar@email.com",
    password: "Password123!!",
    age: 21,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DXJMRTCZ-ee03e0acfefa-512",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I'm going to make the rest of my life the best of my life. Care to share it with me?",
    location: "Birmingham",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Johnathan Jefferies ",
    email: "Johnny@email.com",
    password: "Password123!!",
    age: 28,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DA7X597E-bb57a3722646-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "I can guarantee you won't find anybody else like me.",
    location: "Birmingham",
    height: 1.75,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Suraj Verma",
    email: "suraj@email.com",
    password: "Password123!!",
    age: 34,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DDQZRD96-af59593ac8d8-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Are you sitting on the F5 key? Cause your ass is refreshing.",
    location: "Manchester",
    height: 1.75,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Nazeh Abel",
    email: "nazeh@email.com",
    password: "Password1",
    age: 29,
    img: "https://avatars.githubusercontent.com/u/25328902?v=4",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Girl, are you Wi-Fi? Cuz im feeling the connection!",
    location: "Wolverhampton",
    height: 1.75,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Liana Laurentiu",
    email: "liana@email.com",
    password: "Password1",
    age: 22,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CQNM45PF-48d5b934bdcf-72",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I could be the person you've been dreaming of.",
    location: "Worchester",
    height: 1.75,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Luiz Carlos Fróes",
    email: "luiz@email.com",
    password: "Password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CM398DJS-f6865867d45e-72",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Being both strong and soft is a combination I have mastered!",
    location: "Birmingham",
    height: 1.9,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Conor Kelly",
    email: "conor@email.com",
    password: "Password1",
    age: 26,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CD2RLF0X-a95dbf51e529-72",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Together we could make our dreams come true.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Natasha Mann",
    email: "natasha@email.com",
    password: "Password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02ELC21RPU-91c7f4f57631-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Are you a computer keyboard? Because you're my type.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Lee Farnell",
    email: "lee@email.com",
    password: "Password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02FCQ2F2AC-239609d9569e-72",
    gender: "male",
    sexuality: "gay",
    aboutMe: "I am a Boolean method whose love will always return true.",
    location: "Birmingham",
    height: 1.7,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Maimuna Omar",
    email: "mai@email.com",
    password: "Password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02C7S05FDZ-ed93518b676c-72",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want to inspire and be inspired.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Nina Rodriquez",
    email: "nina.rodriquez@example.com",
    password: "great",
    age: 31,
    img: "https://randomuser.me/api/portraits/women/47.jpg",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "Trying to find love in a hopeless place",
    location: "Coventry",
    height: 1.75,
    build: "athletic",
    seriousness: "low",
  },
  {
    name: "Norma Jensen",
    email: "norma.jensen@example.com",
    password: "77777",
    age: 43,
    img: "https://randomuser.me/api/portraits/women/61.jpg",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Hopefully looking for love in the right place this time!",
    location: "Birmingham",
    height: 1.75,
    build: "athletic",
    seriousness: "high",
  },
  {
    name: "Timmothy Hopkins",
    email: "timmothy.hopkins@example.com",
    password: "wage",
    age: 22,
    img: "https://randomuser.me/api/portraits/men/89.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Looking for fun and maybe more",
    location: "Birmingham",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Avery Berry",
    email: "avery.berry@example.com",
    password: "flash1",
    age: 28,
    img: "https://randomuser.me/api/portraits/women/56.jpg",
    gender: "female",
    sexuality: "gay",
    aboutMe: "Could you be the one I've been looking for all my life?",
    location: "Birmingham",
    height: 1.85,
    build: "curvy",
    seriousness: "medium",
  },
  {
    name: "Reginald Simmons",
    email: "reginald.simmons@example.com",
    password: "hopkins",
    age: 28,
    img: "https://randomuser.me/api/portraits/men/43.jpg",
    gender: "male",
    sexuality: "gay",
    aboutMe: "If I could rate my personality, I'd say good looking!",
    location: "London",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Harvey Gardner",
    email: "harvey.gardner@example.com",
    password: "darren",
    age: 23,
    img: "https://randomuser.me/api/portraits/men/85.jpg",
    gender: "male",
    sexuality: "bisexual",
    aboutMe: "I am good looking (In certain lighting).",
    location: "London",
    height: 1.65,
    build: "slim",
    seriousness: "low",
  },
  {
    name: "Lonnie Stephens",
    email: "lonnie.stephens@example.com",
    password: "hugo",
    age: 27,
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I am just one small person in this big world trying to find real love.",
    location: "Nottingham",
    height: 1.75,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Samuel Burton",
    email: "samuel.burton@example.com",
    password: "555666",
    age: 62,
    img: "https://randomuser.me/api/portraits/men/21.jpg",
    gender: "male",
    sexuality: "bisexual",
    aboutMe: "Once I've found my special someone, my life will be complete.",
    location: "Rugby",
    height: 1.85,
    build: "athletic",
    seriousness: "high",
  },
  {
    name: "Paula Howell",
    email: "paula.howell@example.com",
    password: "mozart",
    age: 29,
    img: "https://randomuser.me/api/portraits/women/91.jpg",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "Don't let idiots ruin your day, date me instead!",
    location: "Bradford",
    height: 1.55,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Marilyn Jackson",
    email: "marilyn.jackson@example.com",
    password: "love123",
    age: 31,
    img: "https://randomuser.me/api/portraits/women/88.jpg",
    gender: "female",
    sexuality: "gay",
    aboutMe:
      "I'm loving, and I'll always look forward to seeing you at the end of each day.",
    location: "London",
    height: 1.6,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Tammy Chambers",
    email: "tammy.chambers@example.com",
    password: "clemson",
    age: 32,
    img: "https://randomuser.me/api/portraits/women/72.jpg",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I'm willing to work hard to make you happy in life.",
    location: "Leeds",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Everett Fisher",
    email: "everett.fisher@example.com",
    password: "pantera1",
    age: 48,
    img: "https://randomuser.me/api/portraits/men/48.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe: "I want someone who can make me smile for no reason.",
    location: "Cardiff",
    height: 1.85,
    build: "large",
    seriousness: "medium",
  },
  {
    name: "Zachary Curtis",
    email: "zachary.curtis@example.com",
    password: "ericsson",
    age: 31,
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe: "I want someone who I can kiss in the pouring rain.",
    location: "Glasgow",
    height: 1.85,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Denise Watts",
    email: "denise.watts@example.com",
    password: "passthie",
    age: 37,
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want someone who can shut me up with kisses..",
    location: "Liverpool",
    height: 1.65,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Misty Craig",
    email: "misty.craig@example.com",
    password: "5050",
    age: 30,
    img: "https://randomuser.me/api/portraits/women/75.jpg",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want to be the best at loving you.",
    location: "Leicester",
    height: 1.6,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Bradley Turner",
    email: "bradley.turner@example.com",
    password: "242424",
    age: 29,
    img: "https://randomuser.me/api/portraits/men/63.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I believe good looks fade, but a good heart keeps you beautiful forever.",
    location: "Oxford",
    height: 1.79,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Kelly Owens",
    email: "kelly.owens@example.com",
    password: "google",
    age: 27,
    img: "https://randomuser.me/api/portraits/women/10.jpg",
    gender: "other",
    sexuality: "bisexual",
    aboutMe: "I believe I am too good a catch to be single.",
    location: "Newcastle",
    height: 1.69,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Max Kennedy",
    email: "max.kennedy@example.com",
    password: "gertrude",
    age: 34,
    img: "https://randomuser.me/api/portraits/men/68.jpg",
    gender: "other",
    sexuality: "straight",
    aboutMe:
      "I am here because I believe life begins at the end of your comfort zone..",
    location: "Belfast",
    height: 1.8,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Julian Sullivan",
    email: "julian.sullivan@example.com",
    password: "coyote",
    age: 31,
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I believe some people cross your path and change your whole direction.",
    location: "Cambridge",
    height: 1.85,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Sebastian Elliott",
    email: "sebastian.elliott@example.com",
    password: "county",
    age: 39,
    img: "https://randomuser.me/api/portraits/men/53.jpg",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Single by choice, just not my choice",
    location: "Cambridge",
    height: 1.95,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Deann Vargas",
    email: "deann.vargas@example.com",
    password: "smeghead",
    age: 29,
    img: "https://randomuser.me/api/portraits/women/31.jpg",
    gender: "female",
    sexuality: "bisexual",
    aboutMe:
      "I want to be the reason you look down at your phone and smile, then walk into a pole.",
    location: "Oxford",
    height: 1.65,
    build: "athletic",
    seriousness: "low",
  },
  {
    name: "George Chapman",
    email: "george.chapman@example.com",
    password: "pics",
    age: 29,
    img: "https://randomuser.me/api/portraits/men/70.jpg",
    gender: "male",
    sexuality: "gay",
    aboutMe: "Well, I'm here. What're your next two wishes?",
    location: "London",
    height: 1.85,
    build: "athletic",
    seriousness: "low",
  },
];

const seedUsers = async () => {
  const promises = userData.map((user) => User.create(user));
  await Promise.all(promises);
};

module.exports = seedUsers;
