const User = require("../models/User");

const userData = [
  {
    name: "Bob Smith",
    email: "bob@email.com",
    password: "password1",
    age: 21,
    img: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe: "tall dark and handsome",
    location: "birmingham",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "John James",
    email: "john@email.com",
    password: "password1",
    age: 24,
    img: "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    gender: "other",
    sexuality: "bisexual",
    aboutMe: "good things come in small packages",
    location: "coventry",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Lynn Peck",
    email: "lynn.peck@example.com",
    password: "password1",
    age: 25,
    img: "https://images.unsplash.com/photo-1542740348-39501cd6e2b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d29tYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I am well-balanced and stable, but willing to let you knock me off my feet",
    location: "Birmingham",
    height: 1.75,
    build: "athletic",
    seriousness: "medium",
  },

  {
    name: "Wanda Mendoza",
    email: "wanda.mendoza@example.com",
    password: "password1",
    age: 41,
    img: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDZ8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "I can guarantee you won't find anybody else like me.",
    location: "Leicester",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },

  {
    name: "Eli Wood",
    email: "eli.wood@example.com",
    age: 28,
    password: "password1",
    img: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "bisexual",
    aboutMe:
      "I am strong enough to protect you and soft enough to melt your heart..",
    location: "Leicester",
    height: 1.65,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Leanne Gallagher",
    email: "leanne_gallag@live.co.uk",
    password: "password1",
    age: 29,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DHCF7M40-9dc481246e1e-512",
    gender: "female",
    sexuality: "bisexual",
    aboutMe:
      "Forget what hurt you in the past. It wasn't me. I'm like the opposite of that person!",
    location: "Coventry",
    height: 1.65,
    build: "large",
    seriousness: "low",
  },

  {
    name: "Fahra Akhlaq",
    email: "Fahra@email.com",
    password: "password1",
    age: 33,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CY4F3BLP-5638e5955f09-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "As long as you think I'm awesome, we will get along just fine.",
    location: "Birmingham",
    height: 1.65,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Sumaia Sorna",
    email: "Sumaia@email.com",
    password: "password1",
    age: 32,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02D2H7RXM1-0f957010b3cf-51212",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I'm not here to be an average partner, I'm here to be an awesome partner.",
    location: "Wolverhampton",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },

  {
    name: "Intisar Mohamed",
    email: "Intisar@email.com",
    password: "password1",
    age: 22,
    img: "https://images.unsplash.com/photo-1582874576091-26fa231ce87c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=327&q=80np",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "I'm going to make the rest of my life the best of my life. Care to share it with me?",
    location: "Birmingham",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Menilek Techane",
    email: "Menilek@email.com",
    password: "password1",
    age: 29,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DPP4KVGD-a0f0aa63ba1d-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Girl, you are hotter than the bottom of my laptop.",
    location: "Birmingham",
    height: 1.85,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Suraj Verma",
    email: "suraj@email.com",
    password: "password1",
    age: 34,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02DDQZRD96-af59593ac8d8-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Are you sitting on the F5 key? Cause your ass is refreshing.",
    location: "Manchester",
    height: 1.75,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Nazeh Abel",
    email: "nazeh@email.com",
    password: "password1",
    age: 29,
    img: "https://avatars.githubusercontent.com/u/25328902?v=4",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Girl, are you Wi-Fi? Cuz im feeling the connection!",
    location: "Wolverhampton",
    height: 1.75,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Liana Laurentiu",
    email: "liana@email.com",
    password: "password1",
    age: 22,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CQNM45PF-48d5b934bdcf-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I could be the person you've been dreaming of.",
    location: "Worchester",
    height: 1.75,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Ben Ashley",
    email: "ben@email.com",
    password: "password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CQCH9C9H-c1b662e4eac1-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "You look like an exception, would love to try and catch you.",
    location: "Birmingham",
    height: 1.8,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Conor Kelly",
    email: "conor@email.com",
    password: "password1",
    age: 26,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02CD2RLF0X-a95dbf51e529-512",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Together we could make our dreams come true.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Natasha Mann",
    email: "natasha@email.com",
    password: "password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02ELC21RPU-91c7f4f57631-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Are you a computer keyboard? Because you're my type.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Lee Farnell",
    email: "lee@email.com",
    password: "password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02FCQ2F2AC-239609d9569e-512",
    gender: "male",
    sexuality: "gay",
    aboutMe: "I am a Boolean method whose love will always return true.",
    location: "Birmingham",
    height: 1.7,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Maimuna Omar",
    email: "mai@email.com",
    password: "password1",
    age: 30,
    img: "https://ca.slack-edge.com/T02C7KG2V0A-U02C7S05FDZ-ed93518b676c-512",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want to inspire and be inspired.",
    location: "Birmingham",
    height: 1.7,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Nina Rodriquez",
    email: "nina.rodriquez@example.com",
    password: "password1",
    age: 23,
    img: "https://images.unsplash.com/photo-1512310604669-443f26c35f52?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjZ8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "Trying to find love in a hopeless place",
    location: "Coventry",
    height: 1.75,
    build: "athletic",
    seriousness: "low",
  },
  {
    name: "Norma Jensen",
    email: "norma.jensen@example.com",
    password: "password1",
    age: 43,
    img: "https://images.unsplash.com/photo-1534180477871-5d6cc81f3920?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Hopefully looking for love in the right place this time!",
    location: "Birmingham",
    height: 1.75,
    build: "athletic",
    seriousness: "high",
  },
  {
    name: "Timmothy Hopkins",
    email: "timmothy.hopkins@example.com",
    password: "password1",
    age: 22,
    img: "https://images.unsplash.com/photo-1567784177951-6fa58317e16b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Looking for fun and maybe more",
    location: "Birmingham",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Avery Berry",
    email: "avery.berry@example.com",
    password: "password1",
    age: 28,
    img: "https://images.unsplash.com/photo-1450297350677-623de575f31c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzV8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "gay",
    aboutMe: "Could you be the one I've been looking for all my life?",
    location: "Birmingham",
    height: 1.85,
    build: "curvy",
    seriousness: "medium",
  },
  {
    name: "Reginald Simmons",
    email: "reginald.simmons@example.com",
    password: "password1",
    age: 28,
    img: "https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    gender: "male",
    sexuality: "gay",
    aboutMe: "If I could rate my personality, I'd say good looking!",
    location: "London",
    height: 1.85,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Harvey Gardner",
    email: "harvey.gardner@example.com",
    password: "password1",
    age: 23,
    img: "https://images.unsplash.com/photo-1523419409543-a5e549c1faa8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=397&q=80",
    gender: "male",
    sexuality: "bisexual",
    aboutMe: "I am good looking (In certain lighting).",
    location: "London",
    height: 1.65,
    build: "slim",
    seriousness: "low",
  },
  {
    name: "Lonnie Stephens",
    email: "lonnie.stephens@example.com",
    password: "password1",
    age: 27,
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I am just one small person in this big world trying to find real love.",
    location: "Nottingham",
    height: 1.75,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Samuel Burton",
    email: "samuel.burton@example.com",
    password: "password1",
    age: 62,
    img: "https://images.unsplash.com/photo-1548449112-96a38a643324?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "bisexual",
    aboutMe: "Once I've found my special someone, my life will be complete.",
    location: "Rugby",
    height: 1.85,
    build: "athletic",
    seriousness: "high",
  },
  {
    name: "Paula Howell",
    email: "paula.howell@example.com",
    password: "password1",
    age: 29,
    img: "https://images.unsplash.com/photo-1548142813-c348350df52b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODN8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "bisexual",
    aboutMe: "Don't let idiots ruin your day, date me instead!",
    location: "Bradford",
    height: 1.55,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Marilyn Jackson",
    email: "marilyn.jackson@example.com",
    password: "password1",
    age: 30,
    img: "https://images.unsplash.com/photo-1530785602389-07594beb8b73?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHx3b21hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "gay",
    aboutMe:
      "I'm loving, and I'll always look forward to seeing you at the end of each day.",
    location: "London",
    height: 1.6,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Tammy Chambers",
    email: "tammy.chambers@example.com",
    password: "password1",
    age: 32,
    img: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I'm willing to work hard to make you happy in life.",
    location: "Leeds",
    height: 1.65,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Everett Fisher",
    email: "everett.fisher@example.com",
    password: "password1",
    age: 48,
    img: "https://images.unsplash.com/photo-1514222709107-a180c68d72b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTU4fHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "male",
    sexuality: "straight",
    aboutMe: "I want someone who can make me smile for no reason.",
    location: "Cardiff",
    height: 1.85,
    build: "large",
    seriousness: "medium",
  },
  {
    name: "Zachary Curtis",
    email: "zachary.curtis@example.com",
    password: "password1",
    age: 31,
    img: "https://images.unsplash.com/photo-1605467195690-9a1e694f3c5d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ5fHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60HxzZWFyY2h8MTQ5fHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "male",
    sexuality: "straight",
    aboutMe: "I want someone who I can kiss in the pouring rain.",
    location: "Glasgow",
    height: 1.85,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Denise Watts",
    email: "denise.watts@example.com",
    password: "password1",
    age: 37,
    img: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want someone who can shut me up with kisses..",
    location: "Liverpool",
    height: 1.65,
    build: "medium",
    seriousness: "high",
  },
  {
    name: "Misty Craig",
    email: "misty.craig@example.com",
    password: "password1",
    age: 30,
    img: "https://images.unsplash.com/photo-1502767882403-636aee14f873?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzF8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60g",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want to be the best at loving you.",
    location: "Leicester",
    height: 1.6,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Bradley Turner",
    email: "bradley.turner@example.com",
    password: "password1",
    age: 29,
    img: "https://images.unsplash.com/photo-1593757147298-e064ed1419e5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTIwfHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I believe good looks fade, but a good heart keeps you beautiful forever.",
    location: "Oxford",
    height: 1.79,
    build: "large",
    seriousness: "high",
  },
  {
    name: "Kelly Owens",
    email: "kelly.owens@example.com",
    password: "password1",
    age: 27,
    img: "https://images.unsplash.com/photo-1589156191108-c762ff4b96ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njh8fHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    gender: "other",
    sexuality: "bisexual",
    aboutMe: "I believe I am too good a catch to be single.",
    location: "Newcastle",
    height: 1.69,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Max Kennedy",
    email: "max.kennedy@example.com",
    password: "password1",
    age: 22,
    img: "https://images.unsplash.com/photo-1615899486509-84e2c782b0da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTU1fHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "other",
    sexuality: "straight",
    aboutMe:
      "I am here because I believe life begins at the end of your comfort zone..",
    location: "Belfast",
    height: 1.8,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Julian Sullivan",
    email: "julian.sullivan@example.com",
    password: "password1",
    age: 31,
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ1fHxtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I believe some people cross your path and change your whole direction.",
    location: "Cambridge",
    height: 1.85,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Sebastian Elliott",
    email: "sebastian.elliott@example.com",
    password: "password1",
    age: 35,
    img: "https://images.unsplash.com/photo-1614533836096-fc5a112c07a4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Single by choice, just not my choice",
    location: "Cambridge",
    height: 1.95,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Deann Vargas",
    email: "deann.vargas@example.com",
    password: "password1",
    age: 29,
    img: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8d29tYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    gender: "female",
    sexuality: "bisexual",
    aboutMe:
      "I want to be the reason you look down at your phone and smile, then walk into a pole.",
    location: "Oxford",
    height: 1.65,
    build: "athletic",
    seriousness: "low",
  },
  {
    name: "George Chapman",
    email: "george.chapman@example.com",
    password: "password1",
    age: 29,
    img: "https://images.unsplash.com/photo-1595860320513-01df382ebdb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "gay",
    aboutMe: "Well, I'm here. What're your next two wishes?",
    location: "London",
    height: 1.85,
    build: "athletic",
    seriousness: "low",
  },
  //new seeds
  {
    name: "Yoda Lee",
    email: "yoda.lee@example.com",
    password: "password1",
    age: 27,
    img: "https://images.unsplash.com/photo-1485043433441-db091a258e5a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "We’ll Never Know If We’re a Great Match Unless You Click that Message Me Button",
    location: "Wolverhampton",
    height: 1.7,
    build: "slim",
    seriousness: "low",
  },
  {
    name: "Caleb Davis",
    email: "Caleb.davis@example.com",
    password: "password1",
    age: 30,
    img: "https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    gender: "male",
    sexuality: "gay",
    aboutMe:
      "Hopeless Romantic? Nope. HOPEFUL Romantic Positively Searching for My Match!”",
    location: "London",
    height: 1.8,
    build: "athletic",
    seriousness: "high",
  },
  {
    name: "Jenny Henry",
    email: "Jenny.henry@example.com",
    password: "password1",
    age: 25,
    img: "https://images.unsplash.com/photo-1541823709867-1b206113eafd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Fun and Quirky Lady Who Can Definitely Promise You Laughs”",
    location: "Glasgow",
    height: 1.5,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Lena Herrera",
    email: "Lena.Herrera@example.com",
    password: "password1",
    age: 28,
    img: "https://images.unsplash.com/photo-1616065298043-67646192dcb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    gender: "female",
    sexuality: "gay",
    aboutMe: "Art-Loving Women: Let’s Paint a Picture of Life Together”",
    location: "Liverpool",
    height: 1.6,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Robin Mitchelle",
    email: "Robin.Mitchelle@example.com",
    password: "password1",
    age: 28,
    img: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "gay",
    aboutMe: "Art-Loving Women: Let’s Paint a Picture of Life Together”",
    location: "Essex",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Reginald Gonzalez",
    email: "reginald.gonzalez@example.com",
    password: "password1",
    age: 30,
    img: "https://images.unsplash.com/photo-1605949405965-d49ada3f9189?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe: "Book Worm Looking to Write the Next Chapter",
    location: "Birmingham",
    height: 1.9,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Kent Allen",
    email: "kent.allen@example.com",
    password: "password1",
    age: 67,
    img: "https://images.unsplash.com/photo-1585807515950-bc46d934c28b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "Man Who Loves the Outdoors and Hiking: Let’s Build a Path Together",
    location: "Bristol",
    height: 1.7,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Ted Harvey",
    email: "ted.harvey@example.com",
    password: "password1",
    age: 22,
    img: "https://images.unsplash.com/photo-1543965170-4c01a586684e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=849&q=80",
    gender: "male",
    sexuality: "gay",
    aboutMe: "Accomplished Man Who’s More Fun Than a 200 Foot Water Slide",
    location: "Sheffield",
    height: 1.8,
    build: "large",
    seriousness: "low",
  },
  {
    name: "Sean Carlson",
    email: "sean.carlson@example.com",
    password: "password1",
    age: 38,
    img: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "Movie Lover Looking for My Co-Star for a Real Life Romantic Comedy",
    location: "Cardiff",
    height: 1.7,
    build: "slim",
    seriousness: "high",
  },
  {
    name: "Courtney Ross",
    email: "courtney.ross@example.com",
    password: "password1",
    age: 25,
    img: "https://images.unsplash.com/photo-1531123414780-f74242c2b052?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Proud Dog Mom Looking for a Partner In Crime",
    location: "Leicester",
    height: 1.6,
    build: "medium",
    seriousness: "medium",
  },
  {
    name: "Maureen Holland",
    email: "maureen.holland@example.com",
    password: "password1",
    age: 26,
    img: "https://images.unsplash.com/photo-1531854253260-44f0d06e3d26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe: "Fitness Lover Looking to Find My Swole Mate",
    location: "Southampton",
    height: 1.7,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Levi Warren",
    email: "levi.warren@example.com",
    password: "password1",
    age: 34,
    img: "https://images.unsplash.com/photo-1570003179394-40b59f9b4a5a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "Math Nerd Looking for Someone to Add to My Life and Multiply the Fun",
    location: "London",
    height: 1.9,
    build: "slim",
    seriousness: "low",
  },
  {
    name: "Tina Rose",
    email: "tina.rose@example.com",
    password: "password1",
    age: 33,
    img: "https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe:
      "Gamer Chick Hitting Restart and Looking for a High Score in Co-Op Mode",
    location: "Preston",
    height: 1.6,
    build: "curvy",
    seriousness: "medium",
  },
  {
    name: "Olivia Cook",
    email: "olivia.cook@example.com",
    password: "password1",
    age: 24,
    img: "https://images.unsplash.com/photo-1484608856193-968d2be4080e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "female",
    sexuality: "gay",
    aboutMe: "Quirky Women Looking for the Mashed to My Potatoes",
    location: "Manchester",
    height: 1.5,
    build: "curvy",
    seriousness: "high",
  },
  {
    name: "Mathew Davidson",
    email: "mathew.davidson@example.com",
    password: "password1",
    age: 36,
    img: "https://images.unsplash.com/photo-1590086782957-93c06ef21604?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "gay",
    aboutMe: "If I could rate my personality, I'd say good looking!",
    location: "Liverpool",
    height: 1.8,
    build: "athletic",
    seriousness: "medium",
  },
  {
    name: "Claire Howell",
    email: "claire.howell@example.com",
    password: "password1",
    age: 28,
    img: "https://images.unsplash.com/photo-1557555187-23d685287bc3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    gender: "female",
    sexuality: "straight",
    aboutMe: "I want to inspire and be inspired.",
    location: "Birmingham",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },
  {
    name: "Ronald Harrison",
    email: "ronald.harrison@example.com",
    password: "password1",
    age: 35,
    img: "https://images.unsplash.com/photo-1595860320513-01df382ebdb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    gender: "male",
    sexuality: "straight",
    aboutMe:
      "I think I’ve discovered the secret of life -you just hang around until you get used to it.",
    location: "Birmingham",
    height: 1.6,
    build: "slim",
    seriousness: "medium",
  },
];

const seedUsers = async () => {
  const promises = userData.map((user) => User.create(user));
  await Promise.all(promises);
};

module.exports = seedUsers;
